---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - extension.networking.istio.io
  resources:
  - virtualserviceconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - extension.networking.istio.io
  resources:
  - virtualserviceconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - extension.networking.istio.io
  resources:
  - virtualserviceconfigs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - networking.istio.io
  resources:
  - virtualservices
  verbs:
  - '*'