# permissions for end users to view virtualserviceconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: virtualserviceconfig-viewer-role
rules:
- apiGroups:
  - extension.networking.istio.io
  resources:
  - virtualserviceconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extension.networking.istio.io
  resources:
  - virtualserviceconfigs/status
  verbs:
  - get
