# permissions for end users to edit virtualserviceconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: virtualserviceconfig-editor-role
rules:
- apiGroups:
  - extension.networking.istio.io
  resources:
  - virtualserviceconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - extension.networking.istio.io
  resources:
  - virtualserviceconfigs/status
  verbs:
  - get
