apiVersion: extension.networking.istio.io/v1
kind: VirtualServiceConfig
metadata:
  name: multiple-v1
spec:
  virtualServiceName: multiple
  # host: multiple.example.com
  host: multiple
  http:
  - name: v1
    match:
      uri:
        prefix: /v1
    route:
      host: multiple
      subset: v1

---
apiVersion: extension.networking.istio.io/v1
kind: VirtualServiceConfig
metadata:
  name: multiple-v2
spec:
  virtualServiceName: multiple
  # host: multiple.example.com
  host: multiple
  http:
  - name: v2
    match:
      uri:
        prefix: /v2
    route:
      host: multiple
      subset: v2
